# Generated by Django 3.2.9 on 2021-11-26 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Creators',
            new_name='Creator',
        ),
    ]
